[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "Simple loading bar and tqdm-like iterator"
authors = [{ name = "LDuheron" }]
readme = "README.md"
license = { text = "MIT" }
dependencies = []
